Bug 1303036 - Use treeherder's job details API instead of a privatebuild artifact;r=bc
mozilla/autophone pull request #59
Opened 2016-09-22 21:10 UTC by wlach

2016-09-23 06:23 UTC, bclary commented on autophonetreeherder.py
> +                {'title': k, 'value': v } for
C:206, 0: No space allowed before bracket
                {'title': k, 'value': v } for
                                        ^ (bad-whitespace)

2016-09-23 07:16 UTC, bclary commented on autophonepulsemonitor.py
> +                project, job['id')))
I don't get the benefit of this nested string interpolation. Can we do it all at once like 

        url = '%s/jobdetail/?repository=%s&job_id=%s' % (
            self.treeherder_url, project, job['id'])

2016-09-23 21:01 UTC, wlach commented on autophonepulsemonitor.py
> +                project, job['id')))
Makes sense, will fix.

2016-10-25 12:32 UTC, bclary requested changes
Works for me as is. I'd like a warning as mentioned.

2016-10-25 12:32 UTC, bclary commented on autophonepulsemonitor.py
> +        if set(info.keys()) != privatebuild_keys:
perhaps LOGGER.warning the missing keys?

2016-10-25 14:24 UTC, wlach commented on autophonepulsemonitor.py
> +        if set(info.keys()) != privatebuild_keys:
Sure :)

2020-08-13 18:56 UTC, bclary commented
This project is no longer active and is being archived.

2020-08-13 18:56 UTC, closed without merging